const actions = {
  LOADING: 'LOADING',
  LOADING_SUBMIT: 'LOADING_SUBMIT',
  DONE_LOADING: 'DONE_LOADING',
  DONE_LOADING_SUBMIT: 'DONE_LOADING_SUBMIT',

  SET_DATA_MY_DOCUMENT: 'SET_DATA_MY_DOCUMENT',
  SET_PARAMS_MY_DOCUMENT: 'SET_PARAMS_MY_DOCUMENT',

  CLEAR_STATE: 'CLEAR_STATE',
};

export default actions;
